### ISSUE TITLE
Not working with Gradle project

### ISSUE THREAD

**Issue by costalfy** [wimdeblauwe/vite-plugin-spring-boot#2]
Hi Wim,
I try your plugin to replace devtools in my gradle projet https://gitlab.com/andycostanza/tinifttt/-/tree/feat_vite_integration?ref_type=heads
But I think, it's only working with maven project because maven copy build stuffs in target folder. With Gradle, the build stuffs are created on build folder and static and template files from thymeleaf are copied on :
* build/resources/main/static
* build/resources/main/templates
I think the solution is near but,  I don't know how to see if we work with gradle or maven

**Comment by wimdeblauwe** [comment]
Version 0.6.0 has been released which should help you use it with Gradle: https://github.com/wimdeblauwe/vite-plugin-spring-boot/releases/tag/0.6.0

Inside `vite.config.js`, you will also need to update the `outDir` to use a Gradle related path:

```
    build: {
        manifest: true,
        rollupOptions: {
            input: [
                '/static/css/application.css'
            ]
        },
        outDir: path.join(__dirname, `./target/classes/static`),
        copyPublicDir: false,
        emptyOutDir: true
    },
```
